#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxIceCream.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IceCreamOrders")]
	public partial class IceCreamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIceCream(IceCream instance);
    partial void UpdateIceCream(IceCream instance);
    partial void DeleteIceCream(IceCream instance);
    #endregion
		
		public IceCreamDataContext() : 
				base(global::AjaxIceCream.Data.Properties.Settings.Default.IceCreamOrdersConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IceCreamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IceCreamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IceCreamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IceCreamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IceCream> IceCreams
		{
			get
			{
				return this.GetTable<IceCream>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IceCream")]
	public partial class IceCream : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Flavor;
		
		private bool _LowFat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFlavorChanging(string value);
    partial void OnFlavorChanged();
    partial void OnLowFatChanging(bool value);
    partial void OnLowFatChanged();
    #endregion
		
		public IceCream()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flavor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Flavor
		{
			get
			{
				return this._Flavor;
			}
			set
			{
				if ((this._Flavor != value))
				{
					this.OnFlavorChanging(value);
					this.SendPropertyChanging();
					this._Flavor = value;
					this.SendPropertyChanged("Flavor");
					this.OnFlavorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowFat", DbType="Bit NOT NULL")]
		public bool LowFat
		{
			get
			{
				return this._LowFat;
			}
			set
			{
				if ((this._LowFat != value))
				{
					this.OnLowFatChanging(value);
					this.SendPropertyChanging();
					this._LowFat = value;
					this.SendPropertyChanged("LowFat");
					this.OnLowFatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
